/**
 * Generated by scripts/sync-contracts.ts
 * Pinned Base Contract Provenance Metadata
 */

export const COMMITTED_UPSTREAM_SHA = '500fe6ef7a7974acf235c84ad0ebb2f28fb5747c';
export const UPSTREAM_REPO = 'bestagentkits/ak-web';
export const SNAPSHOT_TIMESTAMP = '2026-09-02T07:42:23.116Z';

export const SCHEMA_DIGESTS = {
  "constants.ts": "42cc31d09f3cb34d2b083d51223bba6bd3c73b39599043670fc03df6811aef87",
  "blocks-schema.ts": "ad9ba89a2dd2dc5bac56b0932b99463ac17339f0cc1a9a26622b8dad0c177c68",
  "validation.ts": "70ebaad19113f9ce58491f534f03f358d93b15efe7e930af4a9bc4b479e8b1ef",
  "slug.ts": "2a31722dc8d9024b611c32783139c554699c95fb96e42a9094a7f618b2d4aa7f",
  "media-contract.ts": "c6184a96dfdd064a6edd52e0d463b7a04ad2b8eb32959b36ba428cb184153f22"
} as const;

export type ContractFilename = keyof typeof SCHEMA_DIGESTS;
