import { createHash } from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';

export const PINNED_COMMIT_SHA = '500fe6ef7a7974acf235c84ad0ebb2f28fb5747c';
export const UPSTREAM_REPO = 'bestagentkits/ak-web';

const CONTRACT_FILES = [
  { remotePath: 'lib/build-with-ak/constants.ts', localFile: 'constants.ts' },
  { remotePath: 'lib/build-with-ak/blocks-schema.ts', localFile: 'blocks-schema.ts' },
  { remotePath: 'lib/build-with-ak/validation.ts', localFile: 'validation.ts' },
  { remotePath: 'lib/build-with-ak/slug.ts', localFile: 'slug.ts' },
  { remotePath: 'lib/build-with-ak/media-contract.ts', localFile: 'media-contract.ts' },
];

function fetchFromLocalCheckout(localCheckoutDir: string, remotePath: string): string {
  const fullPath = path.join(localCheckoutDir, remotePath);
  if (!fs.existsSync(fullPath)) {
    throw new Error(`File not found in local checkout: ${fullPath}`);
  }
  return fs.readFileSync(fullPath, 'utf8');
}

function fetchFromGitHubApi(repo: string, remotePath: string, ref: string): string {
  try {
    const raw = execSync(`gh api repos/${repo}/contents/${remotePath}?ref=${ref} --jq .content`, {
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    return Buffer.from(raw, 'base64').toString('utf8');
  } catch (error) {
    throw new Error(`Failed to fetch ${remotePath} from ${repo}@${ref} via gh api: ${(error as Error).message}`);
  }
}

export function syncContracts(options?: { localCheckout?: string }) {
  const targetDir = path.join(process.cwd(), 'src', 'contracts', 'generated');
  fs.mkdirSync(targetDir, { recursive: true });

  const digests: Record<string, string> = {};

  for (const { remotePath, localFile } of CONTRACT_FILES) {
    let content: string;
    if (options?.localCheckout) {
      content = fetchFromLocalCheckout(options.localCheckout, remotePath);
    } else {
      content = fetchFromGitHubApi(UPSTREAM_REPO, remotePath, PINNED_COMMIT_SHA);
    }

    // Normalize line endings to LF for deterministic SHA-256
    const normalized = content.replace(/\r\n/g, '\n');
    const digest = createHash('sha256').update(normalized, 'utf8').digest('hex');
    digests[localFile] = digest;

    const outPath = path.join(targetDir, localFile);
    fs.writeFileSync(outPath, normalized, 'utf8');
    console.log(`[sync] Wrote ${localFile} (SHA-256: ${digest.slice(0, 12)}...)`);
  }

  const provenancePath = path.join(process.cwd(), 'src', 'contracts', 'provenance.ts');
  const provenanceContent = `/**
 * Generated by scripts/sync-contracts.ts
 * Pinned Base Contract Provenance Metadata
 */

export const COMMITTED_UPSTREAM_SHA = '${PINNED_COMMIT_SHA}';
export const UPSTREAM_REPO = '${UPSTREAM_REPO}';
export const SNAPSHOT_TIMESTAMP = '${new Date().toISOString()}';

export const SCHEMA_DIGESTS = ${JSON.stringify(digests, null, 2)} as const;

export type ContractFilename = keyof typeof SCHEMA_DIGESTS;
`;

  fs.writeFileSync(provenancePath, provenanceContent.replace(/\r\n/g, '\n'), 'utf8');
  console.log(`[sync] Updated ${provenancePath}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(__filename)) {
  const localIndex = process.argv.indexOf('--local-checkout');
  const localCheckout = localIndex !== -1 ? process.argv[localIndex + 1] : undefined;
  syncContracts({ localCheckout });
}
